name: personal_project
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core_desktop: ^1.0.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.1

  # Di
  get_it: ^7.4.1

  # Utils
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
