name: personal_project
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.3

  # Biometrics
  local_auth: ^2.1.6

  # Storage
  shared_preferences: ^2.1.2
  flutter_secure_storage: ^9.0.0

  # Di
  get_it: ^7.4.1

  # Router
  auto_route: ^7.4.0

  # Utils
  dartz: ^0.10.1
  logger: ^2.0.2+1
  flutter_camera: ^1.0.0
  secure_application: ^3.8.0

  # Bloc
  flutter_bloc: ^8.1.3
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  auto_route_generator: ^7.1.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Trebuc
      fonts:
        - asset: assets/fonts/Trebuchet MS/trebuc.ttf

        - asset: assets/fonts/Trebuchet MS/Trebuchet-MS-Italic.ttf
          style: italic
