// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwhEFLbk7jzFkMnnTpxVHpRpL7eP_1Eoc',
    appId: '1:866126079262:web:502e46b6b71252f256d50f',
    messagingSenderId: '866126079262',
    projectId: 'personal-project-prod',
    authDomain: 'personal-project-prod.firebaseapp.com',
    storageBucket: 'personal-project-prod.appspot.com',
    measurementId: 'G-8N2N9CK3DG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkvZRJg7yXFpXpMQc8PbGSHvfanogP_sQ',
    appId: '1:866126079262:android:b310287c7e6592fd56d50f',
    messagingSenderId: '866126079262',
    projectId: 'personal-project-prod',
    storageBucket: 'personal-project-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkrWYaYcPbFrpUMl9NLwBYCF34IYTrDXU',
    appId: '1:866126079262:ios:d1c4672ccc51dfe956d50f',
    messagingSenderId: '866126079262',
    projectId: 'personal-project-prod',
    storageBucket: 'personal-project-prod.appspot.com',
    iosClientId: '866126079262-i9ij8qj9n25a4c286otekl4nrj6h80c3.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkrWYaYcPbFrpUMl9NLwBYCF34IYTrDXU',
    appId: '1:866126079262:ios:d1c4672ccc51dfe956d50f',
    messagingSenderId: '866126079262',
    projectId: 'personal-project-prod',
    storageBucket: 'personal-project-prod.appspot.com',
    iosClientId: '866126079262-i9ij8qj9n25a4c286otekl4nrj6h80c3.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwhEFLbk7jzFkMnnTpxVHpRpL7eP_1Eoc',
    appId: '1:866126079262:web:8c5d8cde954538a356d50f',
    messagingSenderId: '866126079262',
    projectId: 'personal-project-prod',
    authDomain: 'personal-project-prod.firebaseapp.com',
    storageBucket: 'personal-project-prod.appspot.com',
    measurementId: 'G-2YXHFWH0E0',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBwhEFLbk7jzFkMnnTpxVHpRpL7eP_1Eoc',
    appId: '1:866126079262:web:d4d138082fbbd11256d50f',
    messagingSenderId: '866126079262',
    projectId: 'personal-project-prod',
    authDomain: 'personal-project-prod.firebaseapp.com',
    storageBucket: 'personal-project-prod.appspot.com',
    measurementId: 'G-SY71HJSZHR',
  );
}
